config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/thanks", to: "onboarding#thanks"
  get "/onboarding/step1", to: "onboarding#step1"
  get "/onboarding/step2", to: "onboarding#step2"
  get "/onboarding/step3", to: "onboarding#step3"
  get "/onboarding/step4", to: "onboarding#step4"

  root to: "onboarding#step2",
    constraints: StepConstraint.new("step2")

  root to: "onboarding#step3",
    constraints: StepConstraint.new("step3")

  root to: "onboarding#step4",
    constraints: StepConstraint.new("step4")

  root to: "onboarding#step1"

  post "/create", to: "onboarding#create"
  post "/validate_step", to: "onboarding#validate_step"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id           :integer          not null, primary key
#  first_name   :string
#  last_name    :string
#  email        :string
#  age_range    :string
#  weight_in_lb :integer
#  fave_color   :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  feet_tall    :integer
#  inches_tall  :integer
#

class User < ApplicationRecord
  validates :first_name, :last_name, presence: true, on: :step1
  validates :email, presence: true, on: :step2
  validates :email,
            format: {
              with: /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i
            },
            on: :step2

  validates :age_range, :feet_tall, presence: true, on: :step3
  validates :feet_tall, :inches_tall, numericality: { only_integer: true }, allow_blank: true, on: :step3
  validates :weight_in_lb, numericality: { only_integer: true }, allow_blank: true, on: :step3
  validates :fave_color, presence: true, on: :step4
  # for the final encompassing validation at the end
  validates :first_name,
            :last_name,
            :email,
            :age_range,
            :feet_tall,
            presence: true,
            on: :create

  def height_in_inches
    @height_in_inches ||= feet_tall * 12 + inches_tall.presence
  end

  def height_string_feet_and_inches
    @height_string_feet_and_inches ||= "#{feet_tall}'#{inches_tall}\""
  end
end

app/models/view_models/user.rb
# frozen_string_literal: true

module ViewModels
  class User < SimpleDelegator
    def self.decorate(user)
      new user
    end

    # user has a favorite color and it's not one of the select options
    def submitted_custom_fave_color?
      fave_color.present? && !color_options.include?(fave_color)
    end

    def color_options
      %w[Red Orange Yellow Green Blue Purple Other]
    end

    def age_options
      ["17 or younger", "18-25", "26-35", "36-45", "46 or older"]
    end
  end
end

app/models/view_models/wizard.rb
# frozen_string_literal: true

module ViewModels
  class Wizard
    def self.steps
      %w[step1 step2 step3 step4 thanks].freeze
    end

    def self.next_step(current_step)
      steps[steps.index(current_step) + 1] || step1
    end

    def self.next_step_path(current_step)
      "/onboarding/" + next_step(current_step)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/onboarding_controller.rb
# frozen_string_literal: true

class OnboardingController < ApplicationController
  before_action :wizard_user_from_session, except: [:thanks]
  before_action only: [:step3, :step4] { decorate_user(@wizard_user) }

  def validate_step
    decorate_user(current_step_user)
    if current_step_user.valid?(current_step.to_sym)
      store_state_in_session
      store_place_in_session
      redirect_to action: ViewModels::Wizard.next_step(current_step)
    else
      @wizard_user = current_step_user
      render current_step
    end
  end

  def create
    decorate_user(current_step_user)
    if current_step_user.valid?(current_step.to_sym)
      store_state_in_session
      validate_entire_user
    else
      @wizard_user = current_step_user
      render current_step
    end
  end

  private

  def validate_entire_user
    # validate session user here because it encompasses all of the attrs
    if @wizard_user.save(context: :create)
      reset_session
      flash[:success] = "Good job"
      redirect_to thanks_url
    else
      flash[:error] = @wizard_user.errors.full_messages.join(" / ")
      redirect_to action: current_step
    end
  end

  def wizard_user_from_session
    session["user"] = {} if session["user"].nil?
    @wizard_user = User.new(session["user"])
  end

  def store_state_in_session
    user_params.each { |p, v| session["user"][p] = v }
  end

  def store_place_in_session
    session["step_url"] = {} if session["step_url"].nil?
    session["step_url"] = ViewModels::Wizard.next_step_path(current_step)
  end

  def user_params
    params.require(:user).permit(:last_name,
                                :first_name,
                                :email,
                                :age_range,
                                :feet_tall,
                                :inches_tall,
                                :weight_in_lb,
                                :fave_color)
  end

  def current_step
    params["current_step"]
  end

  def decorate_user(current_user)
    @view_user = ViewModels::User.decorate(current_user)
  end

  def current_step_user
    @current_step_user ||= User.new(user_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_bottom_menu.html.erb
<br>
<div class="form-actions">
  <%= hidden_field_tag :current_step, step %>

  <%= link_to 'Back', previous_step_path, class: "btn btn-outline-secondary btn-lg" %>
  <%= f.submit submit_text, class: "btn btn-primary btn-lg" %>
</div>

app/views/application/_breadcrumbs.html.erb
<nav>
<ul class="breadcrumb">
  <li class=<%='active' if params['action'] == 'step1'%>><%= link_to "Step 1", onboarding_step1_path %></li>
  <li class=<%='active' if params['action'] == 'step2'%>><%= link_to "Step 2", onboarding_step2_path %></li>
  <li class=<%='active' if params['action'] == 'step3'%>><%= link_to "Step 3", onboarding_step3_path %></li>
  <li class=<%='active' if params['action'] == 'step4'%>><%= link_to "Step 4", onboarding_step4_path %></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wizard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "breadcrumbs" %>
    <%= yield %>
  </body>
</html>

app/views/onboarding/step1.html.erb
<h4 class="text-center">Get ready for an unforgettable journey</h4>
<div class="container-fluid">
  <%= simple_form_for(@wizard_user, url: validate_step_path) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name, required: true %>
      <%= f.input :last_name, required: true %>
    </div>

    <%= hidden_field_tag :current_step, "step1" %>

    <%= f.submit "Next", class: "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/onboarding/step2.html.erb
<div class="container-fluid">
  <%= simple_form_for(@wizard_user, url: validate_step_path) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :email, required: true %>
    </div>

    <%= render "bottom_menu", f: f, step: "step2", submit_text: "Next", previous_step_path: onboarding_step1_path %>
  <% end %>
</div>

app/views/onboarding/step3.html.erb
<div class="container-fluid">
  <%= simple_form_for(@wizard_user, url: validate_step_path) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :age_range, collection: @view_user.age_options, label: "Age" %>
    </div>

    <div class="form-inputs">
      <%= f.input :weight_in_lb %>
    </div>

    <div class="form-inputs">
      <%= f.label "Height", required: true %>
      <%= f.input :feet_tall, label: "Feet", required: true %>
      <%= f.input :inches_tall, label: "Inches"%>
    </div>

    <%= render "bottom_menu", f: f, step: "step3", submit_text: "Next", previous_step_path: onboarding_step2_path %>
  <% end %>
</div>

app/views/onboarding/step4.html.erb
<div class="container-fluid">
  <%= simple_form_for(@wizard_user, url: create_path) do |f| %>
    <%= f.error_notification %>

    <% if flash.now[:error] %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>

    <div class="form-inputs color-select">
      <%= f.input :fave_color, collection: @view_user.color_options, label: "Favorite Color" %>
    </div>

    <div class="form-inputs color-text">
      <% if @view_user.submitted_custom_fave_color? %>
        <%= f.input :fave_color, label: "Custom Color", input_html: { value: @wizard_user.fave_color } %>
      <% end %>
    </div>

    <%= render "bottom_menu", f: f, step: "step4", submit_text: "Finish", previous_step_path: onboarding_step3_path %>
  <% end %>
</div>

<%= javascript_include_tag "onboarding/step4" %>

app/views/onboarding/thanks.html.erb
<div class="container-fluid">
  <p class="alert alert-success"><%= flash[:success] if flash[:success]%></p>
  <%= link_to "Want to fill out the form again??", onboarding_step1_path %>
</div>